CREATE TABLE USUARIOS
(
  USERNAME      VARCHAR(50),
  NOMBRE        VARCHAR(100) NOT NULL,
  APELLIDOS     VARCHAR(100) NOT NULL,
  PASSWORD      VARCHAR(50)  NOT NULL,
  ADMINISTRADOR CHAR         NOT NULL,
  AUTOR         CHAR         NOT NULL,
  PRIMARY KEY (USERNAME),
  CHECK (ADMINISTRADOR = 'T' || ADMINISTRADOR = 'F'),
  CHECK (AUTOR = 'T' || AUTOR = 'F')
);

CREATE TABLE ARTICULOS
(
  ID       INTEGER,
  TITULO   VARCHAR(200)  NOT NULL,
  CUERPO   VARCHAR(MAX) NOT NULL,
  USERNAME VARCHAR(50)   NOT NULL,
  FECHA    DATETIME      NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME)
);

CREATE TABLE ETIQUETAS
(
  ID       INTEGER,
  ETIQUETA VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ARTICULO_ETIQUETA
(
  ID_ARTICULO INTEGER,
  ID_ETIQUETA INTEGER,
  PRIMARY KEY (ID_ETIQUETA, ID_ARTICULO),
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID),
  FOREIGN KEY (ID_ETIQUETA) REFERENCES ETIQUETAS (ID)
);

CREATE TABLE COMENTARIOS
(
  ID          INTEGER,
  COMENTARIO  VARCHAR(500) NOT NULL,
  USERNAME    VARCHAR(50)  NOT NULL,
  ID_ARTICULO INTEGER      NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME),
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID)
);

CREATE TABLE ARTICULO_COMENTARIO
(
  ID_ARTICULO   INTEGER,
  ID_COMENTARIO INTEGER,
  PRIMARY KEY (ID_COMENTARIO, ID_ARTICULO),
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID),
  FOREIGN KEY (ID_COMENTARIO) REFERENCES COMENTARIOS (ID)
);
