CREATE TABLE IF NOT EXISTS USUARIOS
(
  USERNAME      VARCHAR(50),
  NOMBRE        VARCHAR(100) NOT NULL,
  APELLIDOS     VARCHAR(100) NOT NULL,
  PASSWORD      VARCHAR(50)  NOT NULL,
  ADMINISTRADOR BOOLEAN      NOT NULL,
  AUTOR         BOOLEAN      NOT NULL,
  PRIMARY KEY (USERNAME)
);

CREATE TABLE IF NOT EXISTS ARTICULOS
(
  ID       BIGINT,
  TITULO   VARCHAR(200)  NOT NULL,
  CUERPO   VARCHAR(MAX)  NOT NULL,
  USERNAME VARCHAR(50)   NOT NULL,
  FECHA    DATETIME      NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME)
);

CREATE TABLE IF NOT EXISTS ETIQUETAS
(
  ID       BIGINT,
  ETIQUETA VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ARTICULO_ETIQUETA
(
  ID_ARTICULO BIGINT,
  ID_ETIQUETA BIGINT,
  PRIMARY KEY (ID_ETIQUETA, ID_ARTICULO),
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID),
  FOREIGN KEY (ID_ETIQUETA) REFERENCES ETIQUETAS (ID)
);

CREATE TABLE IF NOT EXISTS COMENTARIOS
(
  ID          BIGINT,
  COMENTARIO  VARCHAR(500) NOT NULL,
  USERNAME    VARCHAR(50)  NOT NULL,
  ID_ARTICULO BIGINT      NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USERNAME) REFERENCES USUARIOS (USERNAME),
  FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID)
);

CREATE TABLE IF NOT EXISTS IDENTIFICADORES
(
  ID_ARTICULO BIGINT,
  ID_COMENTARIO BIGINT,
  ID_ETIQUETA BIGINT
);
